language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
matrix:
  allow_failures:
    - python:
      - "pypy"
      - "3.2"
      - "3.3"
install:
    # Install pydown library
  - pip install -r requirements.txt --use-mirrors
  - pip install -e . --use-mirrors
script:

